usb: gadget: android: select VIDEOBUF2_VMALLOC if VIDEO_DEV
Otherwise get a link error:
undefined reference to `vb2_vmalloc_memops'

Change-Id: Id307ce9495ecab8bab555acd9e1c2fe12eff15eb
Fixes: 07c1c1f47d3c ("usb: gadget: android: make android gadget independent of VIDEO_DEV")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>