UPSTREAM: drm/bridge: PTN3460 needs DRM_KMS_HELPER
The recently added PTN3460 device driver uses interfaces that
are provided by the KMS helper infrastructure, so we should
explicitly select that to avoid this linker error:

ERROR: "drm_helper_probe_single_connector_modes" [drivers/gpu/drm/bridge/ptn3460.ko] undefined!
ERROR: "drm_helper_connector_dpms" [drivers/gpu/drm/bridge/ptn3460.ko] undefined!

We have to drop the I2C dependency to avoid a circular dependency
chain, but that's ok because DRM already selects I2C.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Dave Airlie <airlied@redhat.com>
(cherry picked from commit 90bde571ad194adb039cb92a11a5b346f15eb610)
Signed-off-by: Andy yan <andy.yan@rock-chips.com>

BUG=chromium:425481
TEST=emerge-veyron_pinky chromeos-kernel-3_14

Change-Id: Ia6753a0031b9feb0c99f7225d2130d61b5cb5c63
Reviewed-on: https://chromium-review.googlesource.com/225087
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>