ANDROID: net: ipv6: fix build failure if IPV6_ROUTE_INFO config is enabled
Pass correct arguments to rt6_get_route_info() function, otherwise
we run into following Kernel build failure:
----------
  CC      net/ipv6/route.o
net/ipv6/route.c: In function ‘rt6_route_rcv’:
net/ipv6/route.c:746:27: error: ‘net’ undeclared (first use in this function)
net/ipv6/route.c:746:27: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [net/ipv6/route.o] Error 1
make[1]: *** [net/ipv6] Error 2
make: *** [net] Error 2
----------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
(cherry picked from commit 2d83217b932001ad92cdadeab7e9cbba4d3dc725
via https://android-review.googlesource.com/#/c/143922/)

BUG=chrome-os-partner:41878
TEST=Enable CONFIG_IPV6_ROUTE_INFO=y, compiles this time

Change-Id: Ie1a81caf165177a585cfc4285dd4f8bf682ea78e
Signed-off-by: Kevin Mihelich <kevin@archlinuxarm.org>
Signed-off-by: Alexandru M Stan <amstan@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/281789
Reviewed-by: Olof Johansson <olofj@chromium.org>