scpi_protocol: fixed compilation error
This adds fixed some errors which are same with following when
compiled rockchip_defconfig without CONFIG_SCPI_PROTOCOL select:

include/linux/scpi_protocol.h:85:12: warning:
'scpi_sys_set_jtagmux_on_off' defined but not used [-Wunused-function]
error, forbidden warning: scpi_protocol.h:85
...

Change-Id: I4545bf47620962e8f7a9a6ed4adc1590efc7dc9e
Signed-off-by: Frank Wang <frank.wang@rock-chips.com>