net: wireless: rockchip_wlan: ssv6xxx: avoid gcc error
With gcc 9:
drivers/net/wireless/rockchip_wlan/ssv6xxx/ssvdevice/ssv_cmd.c:1544:43:
error: argument to 'sizeof' in 'strncat' call is the same expression as
the source; did you mean to use the size of the destination?
[-Werror=sizeof-pointer-memaccess]

Avoid this error by replace sizeof(tmpbf) by 64 while tmpbf is
"char tmpbf[64]". So nothing is changed.

Change-Id: Ib0fe896afd97a73c302ed8a96721ab65dd29b848
Signed-off-by: Tao Huang <huangtao@rock-chips.com>