Revert "UPSTREAM: ASoC: Remove deprecated ENUM/MUX macros"
This reverts commit 424bec26001da4780b61f870c0ff92405dc23353.

This breaks arm-generic as a bunch of sound drivers still use
these helpers.  You probably need to backport more commits before
relanding this.

 chromeos-kernel-3_14-3.14-r193: .../sound/soc/codecs/rt5640.c:821:2: error:
 implicit declaration of function 'SOC_DAPM_VALUE_ENUM' [-Werror=implicit-function-declaration]

A simple grep shows these drivers still use that macro:

 sound/soc/codecs/adav80x.c
 sound/soc/codecs/arizona.h
 sound/soc/codecs/rt5640.c
 sound/soc/codecs/wm2200.c
 sound/soc/codecs/wm5100.c
 sound/soc/codecs/wm5102.c
 sound/soc/codecs/wm5110.c
 sound/soc/codecs/wm8988.c
 sound/soc/codecs/wm8997.c

BUG=chrome-os-partner:29649
TEST=None

Change-Id: Ia8ae02c77383d93ccbdc095d3369ad60b0196360
Reviewed-on: https://chromium-review.googlesource.com/218925
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>