CHROMIUM: crypto: img-hash - disable COMPILE_TEST
On Linux 3.14, x86 implements readl_relaxed, but not writel_relaxed.
Therefore img-hash.c will break the build:

    drivers/crypto/img-hash.c:155:2: error: implicit declaration of function ‘writel_relaxed’ [-Werror=implicit-function-declaration]
    cc1: some warnings being treated as errors
    make[2]: *** [drivers/crypto/img-hash.o] Error 1
    make[1]: *** [drivers/crypto] Error 2

Subsequent Linux releases appear to have added writel_relaxed, so we can
carry this workaround locally.

TEST=compile tested
BUG=chromium:474744

Change-Id: I74036db1965d0de6e93af0609121eb4d4fddbca7
Signed-off-by: Kevin Cernekee <cernekee@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/264460
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>