UPSTREAM: usb: dwc2: move usb_disabled() call to host driver only
Since platform.c will get built for both Host and Gadget, if we leave the
usb_disabled() call in platform.c, it results in the following build error
when (!USB && USB_GADGET) condition is met.

ERROR: "usb_disabled" [drivers/usb/dwc2/dwc2_platform.ko] undefined!

Since usb_disabled() is mostly used to disable USB host functionality, move
the call the host portion for the DWC2 driver.

Acked-by: Paul Zimmerman <paulz@synopsys.com>
BUG=chrome-os-partner:33496
TEST=USB still works

Change-Id: Ib2a228ab34867db341c7f303348929ad1c5cbae8
Signed-off-by: Dinh Nguyen <dinguyen@opensource.altera.com>
Signed-off-by: Felipe Balbi <balbi@ti.com>
Signed-off-by: Doug Anderson <dianders@chromium.org>
(cherry picked from git.kernel.org balbi/usb.git next
 commit f5500ecc90a887d7e65274817733fbe477070559)

Reviewed-on: https://chromium-review.googlesource.com/234740
Reviewed-by: Alexandru Stan <amstan@chromium.org>