UPSTREAM: imx-drm: imx-hdmi: Remove parentheses from returns
Fix the following checkpatch warnings:

ERROR: return is not a function, parentheses are not required
+       return (hdmi->hdmi_data.enc_in_format !=

ERROR: return is not a function, parentheses are not required
+       return ((hdmi->hdmi_data.enc_out_format == YCBCR422_8BITS) &&

ERROR: return is not a function, parentheses are not required
+       return ((hdmi->hdmi_data.enc_in_format == YCBCR422_8BITS) &&

While at it, broke the return code from is_color_space_decimation() and
is_color_space_interpolation() for better readability

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Reviewed-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit ba92b22515e1230661cab7ba2a025910c0636c15)
Signed-off-by: Andy yan <andy.yan@rock-chips.com>

BUG=chromium:425481
TEST=emerge-veyron_pinky chromeos-kernel-3_14

Change-Id: I5700fd465f9ddf5bb0f06147b8a110954f0fb1aa
Reviewed-on: https://chromium-review.googlesource.com/223930
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>