UPSTREAM: usb: dwc2: gadget: fix checkpatch errors
Fix checkpatch errors as belows.

  ERROR: open brace '{' following function declarations go on the next line
  ERROR: space required before the open parenthesis '('

BUG=chrome-os-partner:32735
TEST=Can use dwusb2 ports

Change-Id: I08a94e168a1fda93151b2ffb4a41401cbdbbae75
Signed-off-by: Jingoo Han <jg1.han@samsung.com>
Acked-by: Paul Zimmerman <paulz@synopsys.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Alexandru M Stan <amstan@chromium.org>
(cherry picked from linuxnext
 commit e9ebe7c3b76c24fd5bc2f3b99db453ea71c3072b)
Reviewed-on: https://chromium-review.googlesource.com/222184
Reviewed-by: Julius Werner <jwerner@chromium.org>