CHROMIUM: HACK: tegra: stub out the speedo func
When CONFIG_TEGRA_DVFS is disabled, there's no fallback here, so we get
a build failure on arm-generic boards:
.../drivers/mmc/host/sdhci-tegra.c: In function 'sdhci_tegra_probe':
.../drivers/mmc/host/sdhci-tegra.c:1799:2: error: implicit declaration of
	function 'tegra_get_cpu_speedo_value' [-Werror=implicit-function-declaration]

BUG=chrome-os-partner:32629,chrome-os-partner:33431
TEST=None

Change-Id: I00251b2dbc0bbfa2ab0d5ad4cc9826716719be85
Signed-off-by: Mike Frysinger <vapier@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/231964