FROMLIST: common: dma-mapping: Swap function order
Fix the order of dma_common_contiguous_remap and
dma_common_pages_remap to avoid function declaration errors:

drivers/base/dma-mapping.c: In function 'dma_common_contiguous_remap':
drivers/base/dma-mapping.c:294: error: implicit declaration of
function 'dma_common_pages_remap'
drivers/base/dma-mapping.c:294: warning: assignment makes pointer from
integer without a cast
drivers/base/dma-mapping.c: At top level:
drivers/base/dma-mapping.c:308: error: conflicting types for
'dma_common_pages_remap'
drivers/base/dma-mapping.c:294: error: previous implicit declaration
of 'dma_common_pages_remap' was here

Reported-by: James Hogan <james.hogan@imgtec.com>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Laura Abbott <lauraa@codeaurora.org>
(am from https://patchwork.kernel.org/patch/4783421/)
[djkurtz: map_vm_area(.., &pages) b/c chromeos-3.14 does not have:
 commit f6f8ed47353597dcb895eb4a15a28af657392e72
 mm/vmalloc.c: clean up map_vm_area third argument]
Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:31704
TEST=compile tested on veyron & rush_ryu
TEST=boot tested on rush_ryu w/ v7 series
TEST=boot tested on veyron_pinky w/ v7 series + iommu/drm

Change-Id: I65db739114e8f5816a24a279a2ff1a6dc92e2b83
Reviewed-on: https://chromium-review.googlesource.com/219504
Tested-by: Benson Leung <bleung@chromium.org>
Reviewed-by: Olof Johansson <olofj@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>